<?php

namespace MiAmpaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AmpaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmpaRepository extends EntityRepository
{
}
