<?php

namespace MiAmpaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AmpaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmpaRepository extends EntityRepository
{

	/**
	 * Find Ampa by slug
	 * @param  string $slug Slug.
	 */
	public function findAmpaBySlug($slug)
	{
    	return $this->getEntityManager()
    	->createQuery(
    		'SELECT a from MiAmpaBundle:Ampa a WHERE a.slug=:slug'
    		)
    	->setParameter('slug', $slug)
    	->getSingleResult();
    }
}
